# Generates firmware/pt-leg-display/logo_img.c from a source PNG with alpha.
#
#   .\firmware\tools\make-logo.ps1
#   .\firmware\tools\make-logo.ps1 -Source ..\assets\Other.png -Width 200
#
# Why not lv_img_conv: the npm package needs native canvas bindings that do not
# build on this machine. This produces the same LV_IMG_CF_TRUE_COLOR_ALPHA byte
# layout directly.
#
# Output is pinned to LV_COLOR_DEPTH 16 with LV_COLOR_16_SWAP 1 (what
# firmware/lv_conf.h sets). The generated file #errors if that ever changes,
# rather than rendering garbage.

param(
    [string]$Source = "$PSScriptRoot\..\..\assets\Logo-removebg.png",
    [string]$Out = "$PSScriptRoot\..\pt-leg-display\logo_img.c",
    [int]$Width = 260,
    [string]$Symbol = "logo_img",
    # Repaint every visible pixel this colour, keeping the original alpha. The
    # source artwork is dark navy, which is invisible on the dark UI background;
    # tinting it near-white makes it readable without a light card behind it.
    # Anti-aliased edges survive because only RGB is replaced, never alpha.
    [string]$Tint = ""
)

$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.Drawing

$src = [System.Drawing.Image]::FromFile((Resolve-Path $Source))
$w = $Width
$h = [int][math]::Round($src.Height * ($w / $src.Width))

$bmp = New-Object System.Drawing.Bitmap $w, $h, ([System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
$g = [System.Drawing.Graphics]::FromImage($bmp)
$g.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
$g.Clear([System.Drawing.Color]::Transparent)
$g.DrawImage($src, 0, 0, $w, $h)
$g.Dispose()
$src.Dispose()

$rect = New-Object System.Drawing.Rectangle 0, 0, $w, $h
$data = $bmp.LockBits($rect, [System.Drawing.Imaging.ImageLockMode]::ReadOnly,
                      [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
$bytes = New-Object byte[] ($data.Stride * $h)
[System.Runtime.InteropServices.Marshal]::Copy($data.Scan0, $bytes, 0, $bytes.Length)
$bmp.UnlockBits($data)
$stride = $data.Stride

$tintOn = $Tint -ne ""
if ($tintOn) {
    $hex = $Tint.TrimStart('#')
    $tr = [Convert]::ToInt32($hex.Substring(0, 2), 16)
    $tg = [Convert]::ToInt32($hex.Substring(2, 2), 16)
    $tb = [Convert]::ToInt32($hex.Substring(4, 2), 16)
}

$sw = New-Object System.IO.StreamWriter $Out, $false, ([System.Text.Encoding]::ASCII)
$sw.WriteLine("// GENERATED by firmware/tools/make-logo.ps1 - do not edit by hand.")
$sw.WriteLine("// Source: $(Split-Path -Leaf $Source), scaled to ${w}x${h}, LV_IMG_CF_TRUE_COLOR_ALPHA.")
$sw.WriteLine("#include <lvgl.h>")
$sw.WriteLine("")
$sw.WriteLine("#if LV_COLOR_DEPTH != 16 || LV_COLOR_16_SWAP != 1")
$sw.WriteLine("#error `"logo_img.c was generated for LV_COLOR_DEPTH 16 with LV_COLOR_16_SWAP 1; regenerate it`"")
$sw.WriteLine("#endif")
$sw.WriteLine("")
$sw.WriteLine("#ifndef LV_ATTRIBUTE_MEM_ALIGN")
$sw.WriteLine("#define LV_ATTRIBUTE_MEM_ALIGN")
$sw.WriteLine("#endif")
$sw.WriteLine("")
$sw.WriteLine("const LV_ATTRIBUTE_MEM_ALIGN uint8_t ${Symbol}_map[] = {")

$line = New-Object System.Text.StringBuilder
for ($y = 0; $y -lt $h; $y++) {
    $row = $y * $stride
    for ($x = 0; $x -lt $w; $x++) {
        $i = $row + $x * 4
        $b = $bytes[$i]; $gr = $bytes[$i + 1]; $r = $bytes[$i + 2]; $a = $bytes[$i + 3]
        if ($tintOn) { $r = $tr; $gr = $tg; $b = $tb }
        $c = ((($r -shr 3) -shl 11) -bor (($gr -shr 2) -shl 5) -bor ($b -shr 3))
        # LV_COLOR_16_SWAP 1: high byte first, then low byte, then alpha
        [void]$line.AppendFormat("0x{0:x2},0x{1:x2},0x{2:x2},", ($c -shr 8) -band 0xff, $c -band 0xff, $a)
        if ($line.Length -gt 100) { $sw.WriteLine("  " + $line.ToString()); [void]$line.Clear() }
    }
}
if ($line.Length -gt 0) { $sw.WriteLine("  " + $line.ToString()) }

$sw.WriteLine("};")
$sw.WriteLine("")
$sw.WriteLine("const lv_img_dsc_t ${Symbol} = {")
$sw.WriteLine("  .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,")
$sw.WriteLine("  .header.always_zero = 0,")
$sw.WriteLine("  .header.reserved = 0,")
$sw.WriteLine("  .header.w = $w,")
$sw.WriteLine("  .header.h = $h,")
$sw.WriteLine("  .data_size = $($w * $h) * LV_IMG_PX_SIZE_ALPHA_BYTE,")
$sw.WriteLine("  .data = ${Symbol}_map,")
$sw.WriteLine("};")
$sw.Close()

"generated $Out : ${w}x${h}, $([int](($w * $h * 3) / 1024)) KB of flash"
